import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

//import Notice from "@/components/Notice";
import PageTop from "@/components/PageTop";

import MainPageCarousel from "@/components/MainPageCarousel";
import MainPageSubscription from "@/components/MainPageSubscription";
import MainPageBest from "@/components/MainPageBest";
import MainPageCook from "@/components/MainPageCook";
import MainPageGoods from "@/components/MainPageGoods";
import MainPageBlog from "@/components/MainPageBlog";
import PageBottom from "@/components/PageBottom";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>시화당(詩畵堂) </title>
        <meta charSet="utf-8" />
        <meta
          name="description"
          content="Generated by SmallBird create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*<Notice />*/}
      <PageTop />
      <MainPageCarousel />
      <MainPageSubscription />
      <MainPageBest />
      <MainPageCook />
      <MainPageGoods />
      <MainPageBlog />
      <PageBottom />
    </>
  );
}
